#!/bin/sh

set -e

lb config noauto \
   --apt-indices 'false' \
   --apt-source-archives 'false' \
   --archive-areas 'main contrib non-free' \
   --backports 'true' \
   --bootappend-live 'boot=live components' \
   --clean \
   --debian-installer 'live' \
   --debian-installer-distribution 'daily' \
   --distribution 'buster' \
   --firmware-binary 'false' \
   --firmware-chroot 'false' \
   --image-name 'buster-backports-10.3.2' \
   --iso-volume 'BUSTER_BACKPORTS' \
   --mirror-bootstrap 'https://deb.debian.org/debian' \
   --mirror-binary 'https://deb.debian.org/debian' \
   --mirror-binary-security 'https://deb.debian.org/debian-security' \
   --system 'live' \
   --security 'true' \
   --updates 'true' \
	"${@}"
